library(dplyr)
library(ggplot2)

#calculate compartment switch between two datasets
#input are two cis.vecs file generated by cooltools compute-compartment

comp_switch <- function(data1, data2) {
  data1_e1 <- data1 %>% select(chrom, start, end, E1) %>% filter(E1 !='NA') %>% mutate(binname = paste(chrom, start, end, sep='_'), compartment=ifelse(E1>0, 'A', 'B'))
  data2_e1 <- data2 %>% select(chrom, start, end, E1) %>% filter(E1 !='NA') %>% mutate(binname = paste(chrom, start, end, sep='_'), compartment=ifelse(E1>0, 'A', 'B'))
  
  compartment <- merge(data1_e1[c('binname', 'chrom', 'start', 'end','E1', 'compartment')], data2_e1[c('binname', 'E1', 'compartment')], by='binname')
  compartment <- compartment %>%  mutate(switch = paste(compartment.x, compartment.y, sep=''))
  head(compartment)
  
  summary <- data.frame(table(compartment$switch))
  colnames(summary)[1] <- 'Compartment_Switch'
  summary$Freq <- summary$Freq / sum(summary$Freq )
  summary$Compartment_Switch = factor(summary$Compartment_Switch, levels = c('AA', 'AB', 'BB', 'BA'))
  return(summary)
}

Sertoli<- read.table('Sertoli_10kb.eigs.cis.vecs.txt', sep='\t', header=TRUE)
spg<- read.table('spg_10kb.eigs.cis.vecs.txt', sep='\t', header=TRUE)

PreL <- read.table('PreL_10kb.eigs.cis.vecs.txt', sep='\t', header=TRUE)
L <- read.table('L_10kb.eigs.cis.vecs.txt', sep='\t', header=TRUE)
Z <- read.table('Z_10kb.eigs.cis.vecs.txt', sep='\t', header=TRUE)
P <- read.table('P_10kb.eigs.cis.vecs.txt', sep='\t', header=TRUE)
D <- read.table('D_10kb.eigs.cis.vecs.txt', sep='\t', header=TRUE)
MII <- read.table('MII_10kb.eigs.cis.vecs.txt', sep='\t', header=TRUE)

################################################################################
#compare each stage with PreL
Sertoli_Vs_PreL <- comp_switch(PreL, Sertoli)
spg_Vs_PreL <- comp_switch(PreL, spg)
PreL_Vs_PreL <- comp_switch(PreL, PreL)
L_Vs_PreL <- comp_switch(PreL, L)
Z_Vs_PreL <- comp_switch(PreL, Z)
P_Vs_PreL <- comp_switch(PreL, P)
D_Vs_PreL <- comp_switch(PreL, D)
MII_Vs_PreL <- comp_switch(PreL, MII)

#merge the results for all comparison
stages <- c('Sertoli', 'spg', 'PreL', 'L', 'Z', 'P', 'D', 'MII')
datalist <- list(Sertoli_Vs_PreL, spg_Vs_PreL, PreL_Vs_PreL, L_Vs_PreL, Z_Vs_PreL, P_Vs_PreL, D_Vs_PreL, MII_Vs_PreL)
merged <- Reduce(function(x,y) {merge(x,y, by='Compartment_Switch', all=TRUE)}, datalist)
colnames(merged)[2:9] <- stages
write.table(merged, 'compartment_switch_Vs_PreL_summary.tsv', sep='\t', quote=FALSE)

#melt table for plotting
library(reshape2)
vsPreL <- melt(merged,
                 id.vars = "Compartment_Switch",
                 variable.name = "Stage",
                 value.name = "Fraction")

b1 <- ggplot(data=vsPreL, aes(x=Stage, y=Fraction, fill=Compartment_Switch)) + 
  labs(title = "Compartment changes vs preleptotene")+
  geom_bar(stat="identity")+
  theme_bw()

ggsave('every_stage_vs_PreL_compartment_change.pdf', b1, dpi=300)

######################################################################################
#plot compartment changes between successive meiotic stages 
PreL_Vs_Sertoli <- comp_switch(Sertoli, PreL)
L_Vs_PreL <- comp_switch(PreL, L)
Z_Vs_L <- comp_switch(L, Z)
P_Vs_Z <- comp_switch(Z, P)
D_Vs_P <- comp_switch(P, D)


plot_comp_change <- function(data, figuretitle) {
  b1 <- ggplot(data, aes(x=Compartment_Switch, y=Freq, fill=Compartment_Switch)) +
    geom_bar(stat="identity")+
    labs(title = figuretitle)+
    theme_bw()
  ggsave(paste(figuretitle, '.pdf', sep=''), b1)
  
}

plot_comp_change(PreL_Vs_Sertoli, 'PreL_Vs_Sertoli')
plot_comp_change(L_Vs_PreL, 'L_Vs_PreL')
plot_comp_change(Z_Vs_L, 'Z_Vs_L')
plot_comp_change(P_Vs_Z, 'P_Vs_Z')
plot_comp_change(D_Vs_P, 'D_Vs_P')